### PR TITLE
Added a callback for defrost_max to respond to messages sent from oth…

### PR DESCRIPTION
**Pull request by lillialexis**
…er RVI nodes, and added callback that update the button for defrost_front and defrost_rear

Signed-off-by: Lilli Szafranski (Jaguar - Land Rover) lszafran@jaguarlandrover.com

### CODE REVIEW

**Comment by aeichepdx** [comment]
Why is this closed? It was in review...

**Comment by lillialexis** [comment]
Because I found a bug in the code that I just fixed. I was hoping if I reopened the pull request, my latest commit would be there. I thought github did that. Apparently not? I'll just make a new pull request.

**Comment by lillialexis** [comment]
Oh wait, I refreshed, and now it's saying there are two commits, so I probably can just reopen this pull-request with both commits (the original fix and the bug fix).

**Comment by aeichepdx** [comment]
That's fine - but it does mean that we have to abandon the change in Gerrit and re-import.

**Pull request merged**
